        DD x
        PUSH #2
        POP x
        Terminal node:;
        DD y
        PUSH #10
        POP y
        Terminal node:;
    PUSH [x]
    PUSH #3
    SUB
    JE elsex3
        Terminal node:{
                Terminal node:>
                    PUSH #1
                    Terminal node:||
                    PUSH #0
                Terminal node:;
                PUSH #1
                POP [y]
                Terminal node:;
        Terminal node:}
    JMP endx3
    elsex3:
        Terminal node:{
                Terminal node:>
                    PUSH #1
                    Terminal node:&&
                    PUSH #0
                Terminal node:;
                PUSH #3
                POP [y]
                Terminal node:;
        Terminal node:}
    endx3:
        Terminal node:>
        PUSH [y]
        Terminal node:;
    Terminal node:<EOF>